language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python setup.py install
  - pip install codecov pytest-cov
# command to run tests
script:
  - pytest --cov-report term --cov=src tests
after_success:
  - codecov