language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - pip install codecov pytest-cov
# command to run tests
script:
  - pytest --cov=src tests
after_success:
  - codecov